# Archive Epics - Manage Epic Lifecycle
name: archive-epics
description: "Archive completed epics to a separate file, keeping the main epics.md lean and focused on active work. Supports bi-modal operation: Archive (move completed epics) and Status (view epic completion status)."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/archive-epics"
instructions: "{installed_path}/instructions.md"

# Inputs
variables:
  epics_file: "{planning_artifacts}/epics.md"
  epics_completed_file: "{planning_artifacts}/epics-completed.md"

# Smart input file references
input_file_patterns:
  epics:
    description: "Main epics file with all epics and stories"
    whole: "{planning_artifacts}/epics.md"
    load_strategy: "FULL_LOAD"
  epics_completed:
    description: "Archive file for completed epics"
    whole: "{planning_artifacts}/epics-completed.md"
    load_strategy: "FULL_LOAD"
    optional: true

# Standalone so IDE commands get generated
standalone: true

# No web bundle needed
