# Archive Epics - Manage Epic Lifecycle
name: archive-epics
description: "Full epic and tech-spec archiving: moves completed epics to epics-completed.md, relocates story files to archive/epic-X/, tech-specs to archive/tech-specs/, and cleans sprint-status.yaml. Keeps workspace lean and context-efficient for AI agents."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/archive-epics"
instructions: "{installed_path}/instructions.md"

# Inputs
variables:
  epics_file: "{planning_artifacts}/epics.md"
  epics_completed_file: "{output_folder}/archive/epics-completed.md"
  implementation_artifacts: "{output_folder}/implementation-artifacts"
  sprint_status_file: "{output_folder}/implementation-artifacts/sprint-status.yaml"
  archive_folder: "{output_folder}/archive"
  tech_specs_folder: "{output_folder}/archive/tech-specs"

# Smart input file references
input_file_patterns:
  epics:
    description: "Main epics file with all epics and stories"
    whole: "{planning_artifacts}/epics.md"
    load_strategy: "FULL_LOAD"
  epics_completed:
    description: "Archive file for completed epics (in archive root)"
    whole: "{output_folder}/archive/epics-completed.md"
    load_strategy: "FULL_LOAD"
    optional: true
  sprint_status:
    description: "Sprint status tracking file"
    whole: "{output_folder}/implementation-artifacts/sprint-status.yaml"
    load_strategy: "FULL_LOAD"
  implementation_artifacts:
    description: "Directory containing story files and tech specs"
    whole: "{output_folder}/implementation-artifacts"
    load_strategy: "DIRECTORY_SCAN"

# Standalone so IDE commands get generated
standalone: true

# No web bundle needed
