-- 055: Add generated_copy column to suggested_bets
-- Stores the persisted copy generated by the LLM, sanitized and with oddLabel enforced.
-- NULL = copy not yet generated. Populated on first preview/posting, cleared when tone config changes.

ALTER TABLE suggested_bets ADD COLUMN generated_copy TEXT;
