#!/bin/bash
set -euo pipefail

echo "============================================"
echo " bets-estatistica - Dev Container Setup"
echo "============================================"

# -------------------------------------------
# 1. Install project dependencies
# -------------------------------------------
echo ""
echo "[1/3] Installing project dependencies..."
npm install
cd admin-panel && npm install && cd ..

# -------------------------------------------
# 2. Generate .env files (pointing to Supabase Dev remote)
# -------------------------------------------
echo ""
echo "[2/3] Generating .env files..."

# Keys come from remoteEnv (Codespaces secrets or local .devcontainer/.env)
if [ -z "${SUPABASE_DEV_URL:-}" ] || [ -z "${SUPABASE_DEV_SERVICE_KEY:-}" ]; then
  # Try loading from local .env file (gitignored)
  if [ -f ".devcontainer/.env" ]; then
    set -a
    source .devcontainer/.env
    set +a
  else
    echo ""
    echo "ERROR: Missing Supabase Dev credentials."
    echo "Set Codespaces secrets (SUPABASE_DEV_URL, SUPABASE_DEV_ANON_KEY, SUPABASE_DEV_SERVICE_KEY)"
    echo "or create .devcontainer/.env with those variables."
    exit 1
  fi
fi

# Root .env (bot)
cat > .env <<EOF
# ============================================
# AUTO-GENERATED by dev container setup
# Points to Supabase Dev remote (GuruBet Dev)
# ============================================

# Supabase (dev remote)
SUPABASE_URL=${SUPABASE_DEV_URL}
SUPABASE_SERVICE_KEY=${SUPABASE_DEV_SERVICE_KEY}

# Telegram (fake tokens for local dev — replace with real ones for bot testing)
TELEGRAM_BOT_TOKEN=0000000001:AAFakeToken_DevContainer_XXXXXXXXXXXXXX
TELEGRAM_ADMIN_GROUP_ID=-1001000000002
TELEGRAM_PUBLIC_GROUP_ID=-1001000000001

# OpenAI (fill in for agent testing)
OPENAI_API_KEY=

# External APIs (fill in as needed)
THE_ODDS_API_KEY=
FOOTYSTATS_API_KEY=

# Mercado Pago (fill in for payment testing)
MP_ACCESS_TOKEN=
MP_CHECKOUT_URL=
MP_WEBHOOK_SECRET=
MP_WEBHOOK_PORT=3001

# Server
NODE_ENV=development
TZ=America/Sao_Paulo
PORT=3000
HOST=0.0.0.0

# Dev container: bypass config validation (tokens are fake)
SKIP_CONFIG_VALIDATION=true

# Seed admin password (for re-running seed-admin-users.js)
SEED_ADMIN_PASSWORD=devpassword123
EOF

# Admin panel .env.local
cat > admin-panel/.env.local <<EOF
# ============================================
# AUTO-GENERATED by dev container setup
# Points to Supabase Dev remote (GuruBet Dev)
# ============================================

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_DEV_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_DEV_ANON_KEY:-}
SUPABASE_SERVICE_KEY=${SUPABASE_DEV_SERVICE_KEY}

# Telegram MTProto (fill in for Telegram features)
TELEGRAM_API_ID=
TELEGRAM_API_HASH=

# Encryption key (generate with: openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
EOF

# -------------------------------------------
# 3. Summary
# -------------------------------------------
echo ""
echo "[3/3] Done!"
echo ""
echo "============================================"
echo " Setup complete!"
echo "============================================"
echo ""
echo " Supabase:    ${SUPABASE_DEV_URL} (GuruBet Dev)"
echo " Admin Panel: cd admin-panel && npm run dev"
echo " Bot:         npm run dev"
echo ""
echo " Seed data: 2 groups, 7 matches, 10 bets, 5 members"
echo " Admin login: super@admin.test / devpassword123"
echo ""
echo " Ralph checkpoints: bash .devcontainer/ralph-checkpoints.sh phase1"
echo "============================================"
