#!/bin/bash
set -euo pipefail

echo "============================================"
echo " bets-estatistica - Dev Container Setup"
echo "============================================"

# -------------------------------------------
# 1. Install Supabase CLI
# -------------------------------------------
echo ""
echo "[1/5] Installing Supabase CLI..."
npm install -g supabase@latest

# -------------------------------------------
# 2. Install project dependencies
# -------------------------------------------
echo ""
echo "[2/5] Installing project dependencies..."
npm install
cd admin-panel && npm install && cd ..

# -------------------------------------------
# 3. Initialize and start Supabase local
# -------------------------------------------
echo ""
echo "[3/5] Starting Supabase local..."

if [ ! -f "supabase/config.toml" ]; then
  supabase init
fi

supabase start

# Capture Supabase local credentials
SUPABASE_STATUS=$(supabase status -o json)
LOCAL_API_URL=$(echo "$SUPABASE_STATUS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'))['API URL'])")
LOCAL_ANON_KEY=$(echo "$SUPABASE_STATUS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'))['anon key'])")
LOCAL_SERVICE_KEY=$(echo "$SUPABASE_STATUS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'))['service_role key'])")
LOCAL_DB_URL=$(echo "$SUPABASE_STATUS" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'))['DB URL'])")

echo "  Supabase API:    $LOCAL_API_URL"
echo "  Supabase Studio: http://localhost:54323"

# -------------------------------------------
# 4. Apply SQL migrations
# -------------------------------------------
echo ""
echo "[4/5] Applying SQL migrations..."

MIGRATION_COUNT=0
for f in sql/migrations/*.sql; do
  if [ -f "$f" ]; then
    echo "  Applying: $(basename "$f")"
    psql "$LOCAL_DB_URL" -f "$f" --quiet --no-psqlrc 2>&1 | grep -v "^$" || true
    MIGRATION_COUNT=$((MIGRATION_COUNT + 1))
  fi
done
echo "  Applied $MIGRATION_COUNT migrations."

# -------------------------------------------
# 5. Generate .env files for local development
# -------------------------------------------
echo ""
echo "[5/5] Generating .env files..."

# Root .env (bot)
cat > .env <<EOF
# ============================================
# AUTO-GENERATED by dev container setup
# Points to local Supabase instance
# ============================================

# Supabase (local)
SUPABASE_URL=$LOCAL_API_URL
SUPABASE_SERVICE_KEY=$LOCAL_SERVICE_KEY
DATABASE_URL=$LOCAL_DB_URL

# Telegram (fill in for bot testing)
TELEGRAM_BOT_TOKEN=
TELEGRAM_ADMIN_GROUP_ID=
TELEGRAM_PUBLIC_GROUP_ID=

# OpenAI (fill in for agent testing)
OPENAI_API_KEY=

# External APIs (fill in as needed)
THE_ODDS_API_KEY=
FOOTYSTATS_API_KEY=

# Mercado Pago (fill in for payment testing)
MP_ACCESS_TOKEN=
MP_CHECKOUT_URL=
MP_WEBHOOK_SECRET=
MP_WEBHOOK_PORT=3001

# Server
NODE_ENV=development
TZ=America/Sao_Paulo
PORT=3000
HOST=0.0.0.0
EOF

# Admin panel .env.local
cat > admin-panel/.env.local <<EOF
# ============================================
# AUTO-GENERATED by dev container setup
# Points to local Supabase instance
# ============================================

NEXT_PUBLIC_SUPABASE_URL=$LOCAL_API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$LOCAL_ANON_KEY
SUPABASE_SERVICE_KEY=$LOCAL_SERVICE_KEY

# Telegram MTProto (fill in for Telegram features)
TELEGRAM_API_ID=
TELEGRAM_API_HASH=

# Encryption key (generate with: openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
EOF

echo ""
echo "============================================"
echo " Setup complete!"
echo "============================================"
echo ""
echo " Supabase Studio: http://localhost:54323"
echo " Admin Panel:     cd admin-panel && npm run dev"
echo " Bot:             npm run dev"
echo ""
echo " .env files generated with local Supabase credentials."
echo " Fill in TELEGRAM_BOT_TOKEN, OPENAI_API_KEY, etc. as needed."
echo "============================================"
